name: Release version and NPM publish manually

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Configure Git'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: 'Releasing app'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run tag:generate
          git push --follow-tags origin main
          npm run release
      - name: 'Trigger badged'
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: 'generate-coverall-report'
